version: '3.9'

services:




  db:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: electronic_store
    ports:
      - '3308:3306'
    volumes:
      - mydb:/var/lib/mysql
  ecom:
    build: ./app/Dockerfile
    #image: "sagarkumar99/foodapp:latest"
    ports:
      - "9091:9090"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306

volumes:
  mydb:
